{
	"vid": "3e41c1a6-10bc-11e9-bd85-fcaa147e860e",
	"topic": "Django -- Content spoofing possibility in the default 404 page",
	"affects": [
		{
			"name": [
				"py27-django111",
				"py35-django111",
				"py36-django111",
				"py37-django111"
			],
			"range": [
				{
					"lt": "1.11.18"
				}
			]
		},
		{
			"name": [
				"py35-django20",
				"py36-django20",
				"py37-django20"
			],
			"range": [
				{
					"lt": "2.0.10"
				}
			]
		},
		{
			"name": [
				"py35-django21",
				"py36-django21",
				"py37-django21"
			],
			"range": [
				{
					"lt": "2.1.5"
				}
			]
		}
	],
	"description": {
		"xmlns": "http://www.w3.org/1999/xhtml",
		"text": "\n\t<p> Django security releases issued reports:</p>\n\t<blockquote cite=\"https://www.djangoproject.com/weblog/2019/jan/04/security-releases/\">\n\t  <p>An attacker could craft a malicious URL that could make spoofed content\n\t    appear on the default page generated by the django.views.defaults.page_not_found()\n\t    view.</p>\n\t</blockquote>\n      "
	},
	"references": {
		"url": [
			"https://www.djangoproject.com/weblog/2019/jan/04/security-releases/"
		],
		"cvename": [
			"CVE-2019-3498"
		]
	},
	"dates": {
		"discovery": "2019-01-03",
		"entry": "2019-01-05"
	}
}
