{
	"vid": "d01d10c7-de2d-11e0-b215-00215c6a37bb",
	"topic": "django -- multiple vulnerabilities",
	"affects": [
		{
			"name": [
				"py23-django",
				"py24-django",
				"py25-django",
				"py26-django",
				"py27-django",
				"py30-django",
				"py31-django"
			],
			"range": [
				{
					"lt": "1.3.1",
					"ge": "1.3"
				},
				{
					"lt": "1.2.7",
					"ge": "1.2"
				}
			]
		},
		{
			"name": [
				"py23-django-devel",
				"py24-django-devel",
				"py25-django-devel",
				"py26-django-devel",
				"py27-django-devel",
				"py30-django-devel",
				"py31-django-devel"
			],
			"range": [
				{
					"lt": "16758,1"
				}
			]
		}
	],
	"description": {
		"xmlns": "http://www.w3.org/1999/xhtml",
		"text": "\n\t<p>The Django project reports:</p>\n\t<blockquote cite=\"https://www.djangoproject.com/weblog/2011/sep/09/security-releases-issued/\">\n\t  <p>Please reference CVE/URL list for details</p>\n\t</blockquote>\n      "
	},
	"references": {
		"url": [
			"https://www.djangoproject.com/weblog/2011/sep/09/security-releases-issued/"
		]
	},
	"dates": {
		"discovery": "2011-09-09",
		"entry": "2011-09-13",
		"modified": "2011-11-01"
	}
}
