{
	"vid": "d3e023fb-6e88-11ec-b948-080027240888",
	"topic": "Django -- multiple vulnerabilities",
	"affects": [
		{
			"name": [
				"py37-django22",
				"py38-django22",
				"py39-django22"
			],
			"range": [
				{
					"lt": "2.2.26"
				}
			]
		},
		{
			"name": [
				"py37-django32",
				"py38-django32",
				"py39-django32"
			],
			"range": [
				{
					"lt": "3.2.11"
				}
			]
		},
		{
			"name": [
				"py37-django40",
				"py38-django40",
				"py39-django40"
			],
			"range": [
				{
					"lt": "4.0.1"
				}
			]
		}
	],
	"description": {
		"xmlns": "http://www.w3.org/1999/xhtml",
		"text": "\n\t<p>Django Release  reports:</p>\n\t<blockquote cite=\"https://www.djangoproject.com/weblog/2022/jan/04/security-releases/\">\n\t  <p>CVE-2021-45115: Denial-of-service possibility in UserAttributeSimilarityValidator.</p>\n\t  <p>CVE-2021-45116: Potential information disclosure in dictsort template filter.</p>\n\t  <p>CVE-2021-45452: Potential directory-traversal via Storage.save().</p>\n\t</blockquote>\n      "
	},
	"references": {
		"url": [
			"https://www.djangoproject.com/weblog/2022/jan/04/security-releases/"
		],
		"cvename": [
			"CVE-2021-45115",
			"CVE-2021-45116",
			"CVE-2021-45452"
		]
	},
	"dates": {
		"discovery": "2021-12-20",
		"entry": "2022-01-06"
	}
}
