{
	"vid": "dc132c91-2b71-11eb-8cfd-4437e6ad11c4",
	"topic": "mutt -- authentication credentials being sent over an unencrypted connection",
	"affects": [
		{
			"name": [
				"mutt"
			],
			"range": [
				{
					"lt": "2.0.2"
				}
			]
		}
	],
	"description": {
		"xmlns": "http://www.w3.org/1999/xhtml",
		"text": "\n\t<p>Kevin J. McCarthy reports:</p>\n\t<blockquote cite=\"https://gitlab.com/muttmua/mutt/-/commit/04b06aaa3e0cc0022b9b01dbca2863756ebbf59a\">\n\t    <p>Mutt had incorrect error handling when initially connecting to an IMAP\n\t       server, which could result in an attempt to authenticate without enabling TLS.</p>\n\t</blockquote>\n      "
	},
	"references": {
		"url": [
			"https://gitlab.com/muttmua/mutt/-/commit/04b06aaa3e0cc0022b9b01dbca2863756ebbf59a"
		],
		"cvename": [
			"CVE-2020-28896"
		]
	},
	"dates": {
		"discovery": "2020-11-20",
		"entry": "2020-11-20"
	}
}
