{
  "vid": "ec41c3e2-129c-11dd-bab7-0016179b2dd5",
  "topic": "python -- Integer Signedness Error in zlib Module",
  "affects": [
    {
      "name": [
        "python23"
      ],
      "range": [
        {
          "lt": "2.3.6_1"
        }
      ]
    },
    {
      "name": [
        "python24"
      ],
      "range": [
        {
          "lt": "2.4.5_1"
        }
      ]
    },
    {
      "name": [
        "python25"
      ],
      "range": [
        {
          "lt": "2.5.2_2"
        }
      ]
    }
  ],
  "description": {
    "xmlns": "http://www.w3.org/1999/xhtml",
    "text": "\n\t<p>Justin Ferguson reports:</p>\n\t<blockquote cite=\"http://bugs.python.org/issue2586\">\n\t  <p>Integer signedness error in the zlib extension module in Python\n\t    2.5.2 and earlier allows remote attackers to execute arbitrary code\n\t    via a negative signed integer, which triggers insufficient memory\n\t    allocation and a buffer overflow.</p>\n\t</blockquote>\n      "
  },
  "references": {
    "url": [
      "http://securityreason.com/securityalert/3802",
      "http://bugs.python.org/issue2586"
    ],
    "cvename": [
      "CVE-2008-1721"
    ],
    "bid": [
      "28715"
    ]
  },
  "dates": {
    "discovery": "2008-04-10",
    "entry": "2008-04-25",
    "modified": "2008-04-28"
  }
}
